version: "3.8"

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: github-crm-server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - ./.env.server
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: github-crm-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./.env.client
    depends_on:
      - app

  postgres:
    image: postgres:15-alpine
    container_name: github-crm-postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: github-crm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:
