FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install sequelize-cli globally
RUN npm install -g sequelize-cli

# Expose the port the app runs on
EXPOSE 8080

# Command to run migrations and start in dev mode
CMD ["/bin/sh", "-c", "npm install && npx sequelize-cli db:migrate && npm run start:dev"]